name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://coloroswebsitefs.coloros.com/coloroswebsite-coloros-com/null_20210715141149/PBEM00_11_OTA_3220_all_EV9Qm62kk7GT.ozip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  ZIP_NAME: color.ozip
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with XiaoxinSGSI setup script
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             git clone https://github.com/bkerler/oppo_ozip_decrypt.git >/dev/null
             cd oppo_ozip_decrypt
             sudo apt install python3-pip
             pip3 install -r requirements.txt
             aria2c -c -x16 -s20 -j20 -o $ZIP_NAME $ROM_URL
             ./ozipdecrypt.py $ZIP_NAME
             sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python-pip brotli liblz4-tool gawk aria2        
             cd .. && sudo bash ./url2GSI.sh -c --$BUILD_TYPE $GITHUB_WORKSPACE/ErfanGSIs/oppo_ozip_decrypt/$ZIP_NAME $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              zip -r GSI.zip ./*
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"
              
       - name: upload gof
         run: |
            curl -sL https://git.io/file-transfer | sh
            ./transfer gof $GITHUB_WORKSPACE/ErfanGSIs/output/upload/GSI.zip
            
         
            
